version: "3.9"
services:
  mysql-course-service:
    image: mysql:latest
    ports:
      - "3307:3307"
    container_name: mysql-container
    networks:
      - course-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  course-service:
      container_name: course-container
      build: ./
      networks:
        - course-net
      ports:
        - "8084:8084"
      depends_on:
        - mysql-course-service
      restart: always

networks:
  course-net:
    driver: bridge

